[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solrl_registry = "GUo5ybeouLfzNAG98F99xeARFYsGBosu7qrp8ddy2k2u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"
